// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdenrfcugyevyfvznevo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkZW5yZmN1Z3lldnlmdnpuZXZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyNDI1NjQsImV4cCI6MjA4ODgxODU2NH0.rvSjos965bHvuzdh9zoHEmuJJ9DUbdrHk5mB-_CUz_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});